### ISSUE TITLE
Does not support non-player accounts such as Towny town accounts

### ISSUE THREAD

**Issue by DrkMatr1984** [EDGRRRRs/DivinityEconomy#55]
**Describe the bug**
Non-Player accounts such as towny town accounts don't work as player is null.
**To Reproduce**
1. Create Town
2. Place money into town bank
3. /t bal or even /t throws an error
**Expected behavior**

**Screenshots**
[Pastebin
](https://pastebin.com/1BLMu1QU)
**Context**
Server Version: 1.18.1
Server Type(Spigot/Paper): Paper
Additional Information:

**Comment by EDGRRRRs** [comment]
Hello @DrkMatr1984 

check releases here for updated source.
https://github.com/EDGRRRRs/DivinityEconomy/releases

**Comment by DrkMatr1984** [comment]
Thanks! I'll check it out 🤘

**Comment by EDGRRRRs** [comment]
You can access the prebuilt jars via the store link under "about" on the main github page.

**Comment by DrkMatr1984** [comment]
Ok, you sold me on your project :P I'll support you! Please keep the updates rollin.

**Comment by EDGRRRRs** [comment]
Awesome! feel free to drop any bug reports and feature suggestions.
I'll find the time to put the page back up on spigot too. Been extremely busy recently!

**Comment by DrkMatr1984** [comment]
Aww shoot, I paid but don't know how to access the plugin. I thought I was signed in but maybe I wasn't. Anyway my email was either DrkMatr1984@aol.com for DrkMatr1984@gmail.com and my MC name is Myekaan (signin for your website)

**Comment by EDGRRRRs** [comment]
You should receive an email containing the download link, I’ve resent it to
you in case you didn't get it. Your email was correct.

**Comment by DrkMatr1984** [comment]
How to change initial pricing? A wooden pickaxe sold for 1660 on first handsell :O
https://i.imgur.com/UlEj72s.png

**Comment by EDGRRRRs** [comment]
If you check info.txt there’s a file that explains all the settings.
You can do a few things:
1. In materials.yml you can change the individual quantity of items,
increasing will decrease the price and decreasing with increase the price.

Next in config
2. You can change the “Buy / Sell Scale” which is essentially just
multiplied with the value of the item. So if the item is worth 1,660
dollars, a scale of .1 in the config will yield a final price of 10% of
1,660. As per the default I think it’s 1.0 and .9 for buying and selling.
Make sure buying is higher or people can sell things for more than they
bought them.
3. Tweak the base quantity, which does several things. Such as altering the
rate of change as item quantities change. And also changes the magnitude of
the values.

More specific information in that info.txt file.

**Comment by DrkMatr1984** [comment]
For some reason the Balance on the town account resets on server restart. I'm not sure why, because the yml file for the town's UUID in the data folder shows correctly on deposit. But after restart, resets the yml file to balance of 0.

**Comment by DrkMatr1984** [comment]
Player balance functions as intended tho I might add.

**Comment by EDGRRRRs** [comment]
Does this problem also occur for player balances?

**Comment by DrkMatr1984** [comment]
Nah, just the Town account

**Comment by EDGRRRRs** [comment]
How rather odd, I can’t work on fixing that today however I can give it a
go tomorrow. That is really odd though as I can’t think of anything the Div
Econ code would be doing to reset it. Other than some sort of uuid
mismatching.

**Comment by DrkMatr1984** [comment]
Yeah, I don't know. I did some further testing and found out the town's yml storage file is reset on server load, not shutdown. On shutdown the file retains the balance.

**Comment by EDGRRRRs** [comment]
I've figured out the cause of the problem but there's no simple solution without alot of jank and spaghetti. So i'm going to do a small bit of rewriting for the economy stuff. Can also implement some new features just to make it better. The original economy code I wrote was more of a temporary solution that ended up never being recoded so it's about time I did this anyway :D
That's why I didn't push the update yesterday, might be able to get it done today or atleast by the end of the week( but hopefully today )

**Comment by EDGRRRRs** [comment]
Deleted duplicate message^

I've pushed an update just now that fixes the original way of working around these issues that was broken.. "Preferred Provider" in settings was designed to let the user configure which economy plugin handles everything. Unfortunately it was broken.

Also some other goodies, working on the economy rework now which will be 1.18.3RC2.

Currently I've uploaded 1.18.3RC1, which will be dropped into your email soon, in the future I'm going to have the website provide the user with a licence key which can be used to download from another store, but that's not for a while now.

**Comment by DrkMatr1984** [comment]
Yeah, I tried using essentials as a workaround. I'll do that for now. Thanks!

**Comment by EDGRRRRs** [comment]
Hopefully you don't run into any new bugs, if so drop them my way and I'll get onto fixing them.

**Comment by EDGRRRRs** [comment]
I've pushed quite a big update, including the final 1.18.3 RC jar to your email. If you encounter any issues, let me know.
Here's a summary of the changes:

- Fixed #55 - Complete re-write of economy backend with some new features.
- Introducing smart player storage with settings (Smart Storage Max Size). Dynamically stores the most used players in memory.
- Introducing new player economy logs which logs player transactions in their respective userdata files.
- Introducing comments inside the log file.
- introducing 2 new settings for setting the max and minimum prices for items.
- Added money suffix setting.
- Added papi setting.
- Added new setting "Ignore Save Messages" which allows the user to disable the x.yml was saved message that occurs every 10 minutes, by default.
- Fixed "Preferred Provider" setting not being obeyed properly. Issue 55 can now be fixed through the use of a different economy provider. Such as setting "Preferred Provider" to "Essentials" or another provider. Providers can be found on the startup screen for DivinityEconomy.
- Removed info.txt

**Comment by EDGRRRRs** [comment]
This won't be fully fixed for another day, I did test this however it seems to have changed its mind about working. It seems to want to use deprecated vault api methods that aren't really supposed to be used, and although I've programmed them to work, I've not fully programmed the deprecated functions to be friendly with the non-deprecated functions. I.E player balances use uuid's and towny likes to use player names (this is dumb) instead.

**Comment by DrkMatr1984** [comment]
Not sure why but I am still getting errors:
https://www.toptal.com/developers/hastebin/ukijumuzor.sql

**Comment by EDGRRRRs** [comment]
Checkout https://github.com/EDGRRRRs/DivinityEconomy/releases/tag/1.18.4-RC2
Turns out I updated all the code but forgot to actually use it in one of the old methods. 2 Line changer to fix the problem.
Let me know about anything else, let all the bugs be squashed.
